import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'es' | 'en';

const LANGUAGE_STORAGE_KEY = '@fitnesspro_language_preference';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  toggleLanguage: () => Promise<void>;
  t: (key: string, fallback?: string) => string;
}

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  es: {
    // Tabs de navegación
    'tabs.workout': 'Entrenamiento',
    'tabs.nutrition': 'Nutrición',
    'tabs.progress': 'Mi Progreso',
    'tabs.profile': 'Perfil',

    // General
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',
    'common.search': 'Buscar',
    'common.loading': 'Cargando...',
    'common.confirm': 'Confirmar',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.quantity': 'Cantidad',

    // Nutrición - Encabezado y Pestañas
    'nutrition.screen_subtitle': 'BALANCE ENERGÉTICO & ALIMENTACIÓN',
    'nutrition.screen_title': 'Nutrición Diaria',
    'nutrition.tab_balance': 'Mi Balance',
    'nutrition.tab_suggested': 'Plan Sugerido',
    'nutrition.tab_coach_short': 'Coach',
    'nutrition.tab_coach': 'Plan del Coach & PDF',

    // Balance Energético
    'nutrition.balance_title': 'BALANCE ENERGÉTICO DE HOY',
    'nutrition.total_expenditure': 'GASTO TOTAL',
    'nutrition.exp_sub': 'TDEE + Entreno + Cardio',
    'nutrition.consumed': 'CONSUMO',
    'nutrition.consumed_sub': 'Comidas registradas',
    'nutrition.tdee_base': 'TDEE Basal',
    'nutrition.strength_routine': 'Rutina Fuerza',
    'nutrition.cardio': 'Cardio',
    'nutrition.deficit_badge': '¡TE ESTÁS AHORRANDO {kcal} KCAL HOY!',
    'nutrition.deficit_desc': 'Estás en déficit calórico. Tu organismo está quemando reservas de grasa corporal para suplir la energía restante.',
    'nutrition.surplus_badge': 'CONSUMISTE {kcal} KCAL DE MÁS HOY',
    'nutrition.surplus_desc': 'Estás en superávit energético por encima de tu gasto diario, idóneo para ganancia de volumen o recuperación muscular.',

    // Macronutrientes y Agua
    'nutrition.macros_title': 'MACRONUTRIENTES CONSUMIDOS',
    'nutrition.protein': 'PROTEÍNA',
    'nutrition.carbs': 'CARBOS',
    'nutrition.fats': 'GRASAS',
    'nutrition.hydration_title': 'HIDRATACIÓN DIARIA',
    'nutrition.glass_250': '+250 ml (1 Vaso)',
    'nutrition.bottle_500': '+500 ml (Botella)',

    // Comidas
    'nutrition.meals_section_title': 'REGISTRO DE COMIDAS',
    'nutrition.meals_section_sub': 'Toca "+ Añadir" para buscar alimentos o cargar recientes',
    'nutrition.meal_breakfast': 'Desayuno',
    'nutrition.meal_breakfast_sub': 'Energía para arrancar',
    'nutrition.meal_lunch': 'Almuerzo',
    'nutrition.meal_lunch_sub': 'Comida fuerte',
    'nutrition.meal_snack_afternoon': 'Merienda',
    'nutrition.meal_snack_afternoon_sub': 'Recarga de la tarde',
    'nutrition.meal_dinner': 'Cena',
    'nutrition.meal_dinner_sub': 'Cierre y recuperación',
    'nutrition.meal_snacks': 'Snacks / Colación',
    'nutrition.meal_snacks_sub': 'Entre comidas',
    'nutrition.add_to': 'Añadir a {meal}',
    'nutrition.empty_meal': 'No has registrado alimentos en {meal}.',

    // Buscador y Categorías
    'nutrition.modal_select_food': 'SELECCIONAR ALIMENTO',
    'nutrition.search_placeholder': 'Buscar alimento (banana, avena, pollo, lentejas...)',
    'nutrition.recent_shelf_title': '🕒 ALIMENTOS FRECUENTES / RECIENTES (Últimos 20)',
    'nutrition.no_foods_found': 'No se encontraron alimentos con ese término.',
    'nutrition.create_custom_btn': '¿No encuentras tu alimento? + Crear personalizado',
    'nutrition.cat_all': 'Todos',
    'nutrition.cat_recent': '🕒 Recientes (20)',
    'nutrition.cat_recipes': '🥞 Mis Recetas',
    'nutrition.cat_beverages': '☕ Bebidas, Café & Alcohol',
    'nutrition.cat_fruits': '🍌 Frutas',
    'nutrition.cat_grains': '🌾 Cereales & Carbos',
    'nutrition.cat_veggies': '🥗 Verduras',
    'nutrition.cat_meats': '🥩 Carnes & Huevos',
    'nutrition.cat_legumes': '🫘 Legumbres',
    'nutrition.cat_dairy': '🥛 Lácteos',
    'nutrition.cat_fats': '🥑 Grasas & Frutos Secos',
    'nutrition.cat_supplements': '⚡ Suplementos & Proteínas',
    'nutrition.cat_prepared': '🥪 Platos Típicos',
    'nutrition.cat_custom': '⭐ Mis Alimentos',
    'nutrition.create_recipe_btn': '🥞 + Crear Receta',
    'nutrition.save_as_recipe': '⭐ Guardar como Receta Frecuente',
    'nutrition.recipes_shelf_title': '🥞 MIS RECETAS / PLATOS FRECUENTES',
    'nutrition.recipe_saved_success': '¡Receta guardada exitosamente!',

    // Panel de Porción
    'nutrition.unit_grams': 'Gramos (g)',
    'nutrition.unit_units': 'Unidades (u)',
    'nutrition.unit_slices': 'Rebanadas (reb)',
    'nutrition.quantity_label': 'CANTIDAD:',
    'nutrition.serving_ref': 'Porción ref',
    'nutrition.btn_confirm_add': 'Añadir a {meal}',

    // Crear Alimento Personalizado
    'nutrition.custom_title': 'Crear Alimento Personalizado',
    'nutrition.custom_subtitle': 'NUEVO ALIMENTO',
    'nutrition.custom_name': 'Nombre del alimento:',
    'nutrition.custom_name_placeholder': 'Ej. Batido de avena y frutas',
    'nutrition.custom_category': 'Categoría:',
    'nutrition.custom_unit_label': 'Unidad de medida:',
    'nutrition.custom_per_100g': 'Por 100 gramos',
    'nutrition.custom_per_unit': 'Por 1 unidad / plato',
    'nutrition.custom_kcal': 'Calorías (kcal):',
    'nutrition.custom_prot': 'Proteína (g):',
    'nutrition.custom_carbs': 'Carbohidratos (g):',
    'nutrition.custom_fats': 'Grasas (g):',
    'nutrition.custom_save': 'Guardar Alimento',

    // Plan del Coach
    'coach.no_plan_title': 'Sin plan de nutrición asignado',
    'coach.no_plan_sub': 'Tu Coach aún no ha prescrito un plan alimenticio o pauta en PDF.',
    'coach.check_btn': 'Comprobar',
    'coach.active_badge': 'PLAN ACTIVO',
    'coach.assigned_on': 'Asignado el {date}',
    'coach.daily_goals': 'Metas Diarias Prescritas por el Coach',
    'coach.notes_title': 'Indicaciones del Coach',

    // Perfil y Configuración
    'profile.subtitle': 'CONFIGURACIÓN Y SALUD',
    'profile.title': 'Mi Perfil & Ajustes',
    'profile.language_section': 'IDIOMA DE LA APLICACIÓN',
    'profile.language_sub': 'Selecciona el idioma de la app',
    'profile.lang_es': '🇪🇸 Español',
    'profile.lang_en': '🇺🇸 English',
    'profile.training_prefs_title': 'EXPERIENCIA DE ENTRENAMIENTO',
    'profile.haptics_label': 'Vibración Háptica en Series',
    'profile.haptics_desc': 'Vibrar suavemente al marcar series completadas y al terminar el descanso.',
    'profile.keep_awake_label': 'Pantalla Siempre Activa',
    'profile.keep_awake_desc': 'Evita que la pantalla se apague o bloquee durante tu entrenamiento.',
    'profile.barbell_calc_label': 'Calculadora de Discos de Barra',
    'profile.barbell_calc_desc': 'Mostrar botón para desglosar discos por lado en barra olímpica.',
    'profile.unit_section': 'UNIDAD DE PESO',
    'profile.biometrics_section': 'DATOS BIOMÉTRICOS & GASTO',
    'profile.edit_bio_btn': 'Editar Datos Físicos',
    'profile.weight': 'Peso',
    'profile.height': 'Altura',
    'profile.age': 'Edad',
    'profile.gender': 'Género',
    'profile.activity_level': 'Nivel de Actividad',
    'profile.gender_male': 'Hombre',
    'profile.gender_female': 'Mujer',
    'profile.act_sedentary': 'Sedentario (Poco ejercicio)',
    'profile.act_light': 'Ligero (1-3 días/sem)',
    'profile.act_moderate': 'Moderado (3-5 días/sem)',
    'profile.act_very_active': 'Muy Activo (6-7 días intensos)',
    'profile.logout': 'Cerrar Sesión',
    'profile.delete_account': 'Eliminar Cuenta',

    // Progresión y Rutina Original
    'workout.view_original_plan': 'Ver Plan Original del Coach',
    'workout.original_modal_title': 'Plan Original del Coach',
    'workout.original_modal_subtitle': 'PRESCRIPCIÓN OFICIAL VS TU PROGRESO',
    'workout.adapted_badge': '⚡ Adaptado de tu última sesión',
    'workout.coach_plan_badge': '💪 Plan Oficial del Coach',
    'workout.reset_all_btn': '↺ Restaurar Todo al Plan Original',
    'workout.reset_exercise_btn': 'Restaurar al original',
    'workout.reset_confirm_title': '¿Restaurar rutina original?',
    'workout.reset_confirm_desc': 'Se restablecerán las series, repeticiones y pesos prescritos originalmente por tu Coach.',
    'workout.reset_exercise_confirm_desc': 'Se restablecerán las series y pesos de este ejercicio a lo asignado por tu Coach.',
    'workout.original_values': 'Prescripción del Coach:',
    'workout.current_values': 'Tus valores actuales:',
    'workout.no_modifications': 'Tu rutina actual coincide 100% con la prescripción del Coach.',
    'workout.has_modifications': 'Has adaptado este entrenamiento según tus últimos pesos y series.',
    'workout.series_count': '{count} series',
    'workout.extra_series': 'Serie extra',

    // Gestión de Ejercicios e Inventario Alumno
    'workout.add_exercise_to_session': '+ Agregar Ejercicio a esta sesión',
    'workout.remove_exercise': 'Eliminar ejercicio',
    'workout.remove_exercise_confirm_title': '¿Eliminar ejercicio?',
    'workout.remove_exercise_confirm_desc': '¿Deseas quitar {name} de tu entrenamiento de hoy?',
    'workout.replace_exercise': 'Sustituir ejercicio',
    'workout.library_title': 'Biblioteca de Ejercicios',
    'workout.library_subtitle': 'CATÁLOGO OFICIAL & TUS EJERCICIOS',
    'workout.tab_all': 'Todos',
    'workout.tab_defaults': 'Predeterminados',
    'workout.tab_my_exercises': 'Mis Ejercicios',
    'workout.search_placeholder': 'Buscar por nombre o músculo...',
    'workout.custom_badge': 'Propio',
    'workout.create_custom_btn': '+ Crear Ejercicio',
    'workout.new_exercise_title': 'Crear Ejercicio',
    'workout.new_exercise_sub': 'SE GUARDARÁ EN TU INVENTARIO PERSONAL',
    'workout.exercise_name_label': 'Nombre del Ejercicio',
    'workout.exercise_name_placeholder': 'Ej. Curl de bíceps concentrado en polea',
    'workout.muscle_group_label': 'Grupo Muscular',
    'workout.description_label': 'Descripción / Técnica de Ejecución (Opcional)',
    'workout.description_placeholder': 'Indicaciones clave, postura, tempo o respiración...',
    'workout.media_url_label': 'URL de Video o Foto (Opcional)',
    'workout.media_url_placeholder': 'https://ejemplo.com/video.mp4',
    'workout.save_exercise_btn': 'Guardar y Usar Ejercicio',
    'workout.exercise_saved_success': '¡Ejercicio creado con éxito!',
    'workout.select_exercise_to_add': 'Toca para agregar a tu rutina',
    'workout.create_routine_btn': 'Crear mi Rutina',
    'workout.create_routine_title': 'Crear mi Rutina',
    'workout.create_routine_sub': 'NUEVA RUTINA',
    'workout.routine_title_label': 'Nombre de la Rutina',
    'workout.routine_title_placeholder': 'Ej. Mi Rutina de Fuerza & Hipertrofia',
    'workout.routine_saved_success': '¡Rutina guardada y activada con éxito!',

    // Panel Principal de Rutinas por Grupo Muscular
    'routines.dashboard_title': 'Mis Rutinas',
    'routines.dashboard_subtitle': 'Elige un grupo o crea tu rutina',
    'routines.total_workouts': '{count} entrenamientos completados en total',
    'routines.completed_badge': '🔥 Realizada {count} veces',
    'routines.completed_single': '🔥 Realizada 1 vez',
    'routines.completed_zero': '✨ Por estrenar (0 veces)',
    'routines.last_trained': 'Última vez: {time}',
    'routines.last_today': 'Hoy',
    'routines.last_yesterday': 'Ayer',
    'routines.last_days_ago': 'Hace {days} días',
    'routines.last_never': 'Nunca realizada',
    'routines.start_routine_btn': 'Entrenar Rutina ➔',
    'routines.back_to_dashboard': '← Volver a Mis Rutinas',
    'routines.exercises_count': '{count} ejercicios',
    'routines.create_custom_split': '+ Crear mi Rutina',
    'routines.explore_catalog': 'Catálogo de Ejercicios',
    'routines.in_progress_badge': 'Sesión #{number} en progreso',
    'routines.all_muscle_groups': 'GRUPOS MUSCULARES',
    'routines.not_assigned': 'Sin ejercicios asignados',
    'routines.not_assigned_sub': 'Tu Coach aún no ha cargado ejercicios para este grupo muscular.',
    'routines.train_group': 'Entrenar {group} ➔',
    'routines.assigned_by_coach': 'Asignado por Coach',
    'routines.multiple_splits_notice': 'Puedes entrenar múltiples grupos musculares hoy (ej. Pecho y luego Tríceps). Cada uno sumará su propio +1.',
    'routines.empty_group_alert_title': 'Grupo Muscular Vacío',
    'routines.empty_group_alert_msg': 'Tu Coach aún no ha cargado una rutina para {group}. Puedes solicitarle una asignación o explorar el catálogo de ejercicios.',

    // Reportes Calóricos y Balance Acumulado
    'report.subtitle': 'BALANCE ENERGÉTICO & AHORRO',
    'report.title': 'Reporte Calórico Acumulado',
    'report.open_button': '📊 Ver Reportes de Balance (1D - 1 Mes)',
    'report.tab_1d': '1 Día',
    'report.tab_7d': '7 Días',
    'report.tab_14d': '14 Días',
    'report.tab_30d': '30 Días',
    'report.tab_months': 'Meses',
    'report.deficit_badge': '¡AHORRO CALÓRICO ACUMULADO!',
    'report.surplus_badge': 'SUPERÁVIT ENERGÉTICO ACUMULADO',
    'report.deficit_explanation': 'En este período consumiste menos de lo que gastaste. Este ahorro equivale a grasa corporal reducida.',
    'report.surplus_explanation': 'En este período consumiste un exceso neto de calorías sobre tu gasto diario. Idóneo para fase de volumen o hipertrofia muscular.',
    'report.intake_label': 'CONSUMO TOTAL',
    'report.expenditure_label': 'GASTO TOTAL',
    'report.base_label': 'BASE COTIDIANA',
    'report.exercise_label': 'EJERCICIO TOTAL',
    'report.avg_label': 'Media:',
    'report.strength_cardio_sum': 'Rutinas + Cardio sumados',
    'report.archive_month_title': 'Guardar Cierre de este Mes',
    'report.archive_month_desc': 'Almacena el registro histórico mensual para consultar tu progreso a largo plazo.',
    'report.save_btn': 'Guardar Mes',
    'report.saved_btn': '¡Guardado!',
    'report.daily_breakdown_title': 'DESGLOSE DÍA POR DÍA',
    'report.archives_title': 'HISTORIAL DE MESES ARCHIVADOS',

    // Home / Pantalla Principal de Entrenamiento
    'home.greeting': 'HOLA',
    'home.today_workout': 'Entrenamiento de Hoy',
    'home.lang_esp': '🇪🇸 ESP',
    'home.lang_eng': '🇺🇸 ENG',
    'home.unit_label': 'UNIDAD:',
    'home.system_metric': 'Métrico (kg / cm)',
    'home.system_imperial': 'Imperial (lbs / ft)',
    'home.loading_workout': 'Cargando entrenamiento de hoy...',
    'home.no_routine_title': 'No tienes rutina activa asignada',
    'home.no_routine_sub': 'Tu Coach te asignará un programa personalizado desde su panel en cuanto esté listo.',
    'home.check_again': 'Sincronizar',
    'home.fallback_title': '⚡ Rutina de Inicio Pro Activa',
    'home.fallback_sub': 'Entrena y registra series con normalidad. Pulsa sincronizar para verificar nuevas asignaciones de tu Coach.',
    'home.sync': 'Sincronizar',
    'home.day_badge': 'DÍA {number}',
    'home.view_coach_plan': '💪 Ver Plan Original del Coach',
    'home.start_session': 'INICIAR ENTRENAMIENTO',
    'home.finish_session': 'FINALIZAR SESIÓN',
    'home.finish_btn': 'Finalizar',
    'home.start_btn': 'Iniciar Sesión',
    'home.elapsed_time': 'Tiempo transcurrido',
    'home.stat_calories': 'kcal',
    'home.stat_sets': 'series',
    'home.add_extra_set': '+ Agregar Serie Extra',
    'home.col_set': 'SERIE',
    'home.col_target': 'OBJETIVO',
    'home.col_rpe': 'RPE',
    'home.col_actual': 'REGISTRO',
    'home.col_status': 'ESTADO',
    'home.finish_confirm_title': '¿Finalizar sesión de entrenamiento?',
    'home.finish_confirm_desc': 'Has completado {completed} de {total} series programadas ({rate}%). ¿Deseas dar por concluida la sesión de hoy?',
    'home.btn_finish_save': 'Sí, Finalizar y Guardar',
    'home.btn_keep_training': 'Continuar Entrenando',
    'home.discard_title': '¿Descartar sesión?',
    'home.discard_desc': 'No has completado series de este entrenamiento. ¿Deseas descartarla?',
    'home.discard_btn': 'Descartar',
    'home.rest_timer_title': 'DESCANSO ENTRE SERIES',
    'home.add_cardio_btn': '+ Agregar Cardio o Actividad',

    // Resumen de Entrenamiento (WorkoutSummaryModal)
    'summary.title': '¡Entrenamiento Completado!',
    'summary.subtitle': 'Excelente trabajo. Cada serie y minuto te acerca más a tu mejor versión.',
    'summary.time': 'TIEMPO',
    'summary.calories': 'KCAL',
    'summary.success': 'ÉXITO',
    'summary.volume': 'VOLUMEN',
    'summary.continue_btn': 'Continuar al Inicio',

    // Cardio & Actividades Extra (CardioExtrasSection)
    'cardio.title': 'Cardio y Deportes',
    'cardio.subtitle': 'Cronómetro en vivo y registro de actividades.',
    'cardio.live_timer_badge': 'CRONÓMETRO EN VIVO',
    'cardio.paused_timer_badge': 'CRONÓMETRO EN PAUSA',
    'cardio.elapsed_time': 'Tiempo transcurrido',
    'cardio.estimated_burn': 'Gasto calculado',
    'cardio.pause_btn': 'Pausar',
    'cardio.resume_btn': 'Reanudar',
    'cardio.stop_save_btn': 'Detener y Guardar',
    'cardio.add_activity_btn': '+ Registrar Actividad',
    'cardio.edit_modal_title': 'Modificar Actividad Realizada',
    'cardio.manual_modal_title': 'Registrar Actividad / Deporte',
    'cardio.duration_label': 'Duración (minutos):',
    'cardio.incline_label': 'Inclinación (°):',
    'cardio.speed_label': 'Velocidad (km/h):',
    'cardio.resistance_label': 'Nivel de Resistencia:',
    'cardio.calc_burn_preview': 'Gasto energético estimado:',
    'cardio.start_timer_btn': '⏱️ Iniciar Cronómetro en Vivo',
    'cardio.save_manual_btn': 'Guardar Actividad',
    'cardio.tab_stopwatch': '⏱️ Cronómetro en Vivo',
    'cardio.tab_manual': '✍️ Ingreso Manual',

    // Tipos de Cardio
    'cardio.type.treadmill': 'Caminadora con Inclinación',
    'cardio.type.stairmaster': 'Escalador (StairMaster)',
    'cardio.type.elliptical': 'Elíptica',
    'cardio.type.bike': 'Bicicleta Estática',
    'cardio.type.outdoor_walk': 'Caminata al Aire Libre',
    'cardio.type.running': 'Carrera / Running',
    'cardio.type.outdoor_cycling': 'Ciclismo Exterior',
    'cardio.type.swimming': 'Natación',
    'cardio.type.football': 'Fútbol',
    'cardio.type.tennis': 'Tenis / Pádel',
    'cardio.type.golf': 'Golf (Caminando)',
    'cardio.type.basketball': 'Básquetbol',
    'cardio.type.boxing': 'Boxeo / Artes Marciales',
    'cardio.type.yoga': 'Yoga',
    'cardio.type.pilates': 'Pilates',
    'cardio.type.sports': 'Deportes Varios',
    'cardio.type.other_sport': 'Otra Actividad',

    // Progreso (ProgressScreen)
    'progress.subtitle': 'MÉTRICAS & EVOLUCIÓN',
    'progress.title': 'Mi Progreso Físico',
    'progress.log_weight_btn': '+ Registrar Peso Hoy',
    'progress.attendance_title': 'Registro de Asistencia',
    'progress.weight_chart_title': 'Evolución de Peso',
    'progress.no_weight_records': 'Sin registros de peso aún',
    'progress.no_weight_sub': 'Registra tu peso corporal hoy para ver tu evolución gráfica en {unit}.',
    'progress.log_weight_modal_title': 'Registrar Peso Corporal',
    'progress.weight_input_label': 'Peso en {unit}:',
    'progress.notes_placeholder': 'Notas (ej: ayunas, post-entreno...)',
    'progress.save_weight_btn': 'Guardar Registro',
    'progress.saved_badge': 'Registrado',
    'progress.caloric_exp_title': 'Gasto Calórico & Reportes',
    'progress.caloric_exp_sub': 'Consumo energético en pesas y cardio',
    'progress.period_day': 'Día',
    'progress.period_week': 'Semana',
    'progress.period_month': 'Mes',

    // Perfil adicional
    'profile.title_settings': 'Preferencias & Configuración',
    'profile.lang_label': 'Idioma del Sistema',
    'profile.lang_desc': 'Español o English en toda la app',
    'profile.unit_desc': 'Kilogramos o Libras en ejercicios y peso',
    'profile.bio_title': 'Datos Fisiológicos & Biometría',
    'profile.bio_card_title': 'Parámetros de Gasto Calórico',
    'profile.update_bio_btn': 'Actualizar mis Medidas y Datos',
    'profile.how_it_works': '¿Cómo calculamos IMC, TMB y TDEE? (Explicación científica)',
    'profile.active_membership': 'MEMBRESÍA ACTIVA',
    'profile.inactive_membership': 'MEMBRESÍA INACTIVA / EN PAUSA',
    'profile.inactive_title': 'Acceso a Rutinas y Progreso Restringido',
    'profile.inactive_desc': 'Tu membresía se encuentra en pausa o inactiva. Comunícate con tu Coach para reactivarla.',

    // Inactive Lock
    'lock.title': 'MEMBRESÍA INACTIVA / EN PAUSA',
    'lock.heading': 'Acceso Restringido por tu Coach',
    'lock.message': 'Hola {name}, tu plan de entrenamiento y nutrición se encuentra temporalmente en pausa. Tu Coach puede reactivarlo en cualquier momento.',
    'lock.btn_check': 'Comprobar Estado Nuevamente',
    'lock.btn_contact': 'Contactar a mi Coach',
    'lock.btn_logout': 'Cerrar Sesión',

    // Autenticación & Registro (Auth)
    'auth.brand_subtitle': 'Plataforma de Entrenamiento y Nutrición',
    'auth.welcome_title': 'Bienvenido, Alumno',
    'auth.register_title': 'Registro de Nuevo Alumno',
    'auth.email_label': 'Correo Electrónico',
    'auth.email_placeholder': 'tu@correo.com',
    'auth.password_label': 'Contraseña',
    'auth.password_placeholder': '••••••••',
    'auth.confirm_password_label': 'Confirmar Contraseña',
    'auth.confirm_password_placeholder': '••••••••',
    'auth.full_name_label': 'Nombre y Apellido',
    'auth.full_name_placeholder': 'Ej. Juan Pérez',
    'auth.login_btn': 'Iniciar Sesión',
    'auth.register_btn': 'Crear Cuenta',
    'auth.no_account_prompt': '¿No tienes cuenta?',
    'auth.no_account_link': 'Regístrate aquí',
    'auth.have_account_prompt': '¿Ya tienes cuenta?',
    'auth.have_account_link': 'Inicia sesión',
    'auth.fill_all_fields': 'Por favor completa todos los campos.',
    'auth.password_min_length': 'La contraseña debe tener al menos 6 caracteres.',
    'auth.passwords_dont_match': 'Las contraseñas no coinciden.',
    'auth.invalid_credentials': 'Correo o contraseña incorrectos. Verifica tus datos.',
    'auth.unconfirmed_email': 'Debes confirmar tu correo electrónico antes de ingresar.',
    'auth.pending_activation_title': 'Correo pendiente de activación',
    'auth.pending_activation_desc': 'Revisa tu bandeja de entrada o carpeta de spam para activar tu cuenta ({email}).',
    'auth.resend_activation_btn': 'Reenviar correo de activación',
    'auth.resending': 'Reenviando...',
    'auth.resend_success_title': '¡Enlace reenviado!',
    'auth.resend_success_desc': 'Revisa tu bandeja de entrada o carpeta de spam.',

    // Perfil y Configuración Adicionales
    'profile.session_title': 'Sesión',
    'profile.sign_out_btn': 'Cerrar Sesión',
    'profile.compliance_title': 'Gestión de Datos y Privacidad',
    'profile.compliance_desc': 'En cumplimiento con los lineamientos de Apple App Store, puedes solicitar la eliminación definitiva de tu cuenta y registros personales.',
    'profile.delete_account_btn': 'Eliminar mi cuenta y todos mis datos',
    'profile.bio_modal_subtitle': 'ACTUALIZAR BIOMETRÍA',
    'profile.bio_modal_title': 'Mis Datos Fisiológicos',
    'profile.bio_modal_explain': 'Estos datos son esenciales para calcular de forma fidedigna tu gasto calórico en la rutina, caminadora con inclinación y cardio.',
    'profile.gender_label': 'GÉNERO BIOLÓGICO',
    'profile.weight_label': 'PESO CORPORAL ({unit})',
    'profile.weight_hint': 'En {unit}',
    'profile.height_label': 'ESTATURA',
    'profile.feet_label': 'PIES (FT)',
    'profile.inches_label': 'PULGADAS (IN)',
    'profile.body_type_label': 'COMPOSICIÓN CORPORAL & FÍSICO',
    'profile.body_standard': 'Estándar',
    'profile.body_standard_sub': 'Población general',
    'profile.body_athletic': 'Atlético / Muscular',
    'profile.body_athletic_sub': 'Mayor masa magra (baja grasa)',
    'profile.age_label': 'EDAD',
    'profile.activity_level_label': 'NIVEL DE ACTIVIDAD DIARIA',
    'profile.save_bio_btn': 'Guardar Parámetros',
    'profile.saving_bio': 'Guardando...',
    'profile.unit_conversion_sub': 'Conversión automática en todo el sistema (kg o lbs)',

    // Missing Keys - Perfil y Biometría
    'profile.membership_inactive': 'MEMBRESÍA INACTIVA / EN PAUSA',
    'profile.membership_active': 'MEMBRESÍA ACTIVA',
    'profile.biometrics_section_title': 'Datos Fisiológicos & Biometría',
    'profile.caloric_params_title': 'Parámetros de Gasto Calórico',
    'profile.weight_label_short': 'PESO CORPORAL',
    'profile.height_label_short': 'ESTATURA',
    'profile.physique_profile_label': 'PERFIL FÍSICO',
    'profile.gender_age_label': 'GÉNERO & EDAD',
    'profile.bmi_title': 'Índice de Masa Corporal (IMC)',
    'profile.bmr_title': 'Tasa Metabólica Basal (TMB)',
    'profile.bmr_desc': 'Gasto vital en reposo',
    'profile.tdee_title': 'Gasto Calórico Diario Base',
    'profile.tdee_desc': 'TMB + Actividad laboral/cotidiana (sin entrenar)',
    'profile.how_calculated_btn': '¿Cómo calculamos IMC, TMB y TDEE? (Explicación científica)',
    'profile.unit_label': 'Unidad de Peso',

    // Missing Keys - Coach y Nutrición
    'coach.goals_title': 'Metas Diarias Prescritas por el Coach',
    'nutrition.confirm_add': 'Confirmar y Añadir',
    'nutrition.custom_food_name': 'Nombre del alimento:',
    'nutrition.custom_measure_unit': 'Unidad de medida:',
    'nutrition.custom_calories': 'Calorías (kcal):',
    'nutrition.custom_save_btn': 'Guardar Alimento',

    // Missing Keys - Progreso
    'progress.loading': 'Cargando tu progreso...',

    // Missing Keys - Cardio y Extras
    'cardio.live_timer_btn': 'Iniciar Cronómetro en Vivo',
    'cardio.manual_reg_btn': 'Registro Manual',
    'cardio.select_activity': 'SELECCIONA LA ACTIVIDAD',
    'cardio.time_done': 'TIEMPO REALIZADO (MINUTOS)',
    'cardio.min_time_hint': 'Mínimo 1 min',

    // Missing Keys - Workout Interactivo
    'workout.extra_set_label': 'SERIE AÑADIDA',
    'workout.coach_target_label': 'OBJETIVO COACH',
    'workout.reps_label': 'Reps',
    'workout.weight_label': 'Peso ({unit})',
    'workout.customize_exercise': 'Personalizar',
    'workout.customize_title': 'Personalizar Ejercicio',
    'workout.offline_mode_badge': 'Sin conexión',
    'workout.synced_badge': 'Sincronizado',

    // BioHacker Peptides
    'biohacker.badge_science': '🧬 CIENCIA APLICADA',
    'biohacker.card_title': 'BioHacker Peptides',
    'biohacker.card_subtitle': 'Descubre la vanguardia en péptidos bioactivos, regeneración celular, hipertrofia muscular y longevidad deportiva.',
    'biohacker.cta_explore': 'Explorar Guía Científica',
    'biohacker.tab_peptides': 'Péptidos',
    'biohacker.tab_benefits': 'Beneficios',
    'biohacker.tab_infographic': 'Infografía',
  },
  en: {
    // Navigation Tabs
    'tabs.workout': 'Workout',
    'tabs.nutrition': 'Nutrition',
    'tabs.progress': 'My Progress',
    'tabs.profile': 'Profile',

    // General
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.confirm': 'Confirm',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.quantity': 'Quantity',

    // Nutrition - Header and Tabs
    'nutrition.screen_subtitle': 'ENERGY BALANCE & FOOD LOG',
    'nutrition.screen_title': 'Daily Nutrition',
    'nutrition.tab_balance': 'My Balance',
    'nutrition.tab_suggested': 'Suggested Plan',
    'nutrition.tab_coach_short': 'Coach',
    'nutrition.tab_coach': "Coach's Plan & PDF",

    // Energy Balance
    'nutrition.balance_title': "TODAY'S ENERGY BALANCE",
    'nutrition.total_expenditure': 'TOTAL EXPENDITURE',
    'nutrition.exp_sub': 'TDEE + Workout + Cardio',
    'nutrition.consumed': 'CONSUMED',
    'nutrition.consumed_sub': 'Logged foods',
    'nutrition.tdee_base': 'Base TDEE',
    'nutrition.strength_routine': 'Strength Routine',
    'nutrition.cardio': 'Cardio',
    'nutrition.deficit_badge': "YOU'RE SAVING {kcal} KCAL TODAY!",
    'nutrition.deficit_desc': 'You are in a caloric deficit. Your body is burning fat stores to meet remaining energy requirements.',
    'nutrition.surplus_badge': 'YOU CONSUMED {kcal} KCAL IN SURPLUS TODAY',
    'nutrition.surplus_desc': 'You are in an energy surplus above daily burn, ideal for muscle hypertrophy and recovery.',

    // Macronutrients and Water
    'nutrition.macros_title': 'CONSUMED MACRONUTRIENTS',
    'nutrition.protein': 'PROTEIN',
    'nutrition.carbs': 'CARBS',
    'nutrition.fats': 'FATS',
    'nutrition.hydration_title': 'DAILY HYDRATION',
    'nutrition.glass_250': '+250 ml (1 Glass)',
    'nutrition.bottle_500': '+500 ml (Bottle)',

    // Meals
    'nutrition.meals_section_title': 'MEALS LOG',
    'nutrition.meals_section_sub': 'Tap "+ Add" to search foods or load recent items',
    'nutrition.meal_breakfast': 'Breakfast',
    'nutrition.meal_breakfast_sub': 'Morning fuel',
    'nutrition.meal_lunch': 'Lunch',
    'nutrition.meal_lunch_sub': 'Main mid-day meal',
    'nutrition.meal_snack_afternoon': 'Afternoon Snack',
    'nutrition.meal_snack_afternoon_sub': 'Afternoon recharge',
    'nutrition.meal_dinner': 'Dinner',
    'nutrition.meal_dinner_sub': 'Evening recovery',
    'nutrition.meal_snacks': 'Snacks / Bites',
    'nutrition.meal_snacks_sub': 'Between meals',
    'nutrition.add_to': 'Add to {meal}',
    'nutrition.empty_meal': 'No foods logged for {meal}.',

    // Search and Categories
    'nutrition.modal_select_food': 'SELECT FOOD',
    'nutrition.search_placeholder': 'Search food (banana, oats, chicken, beans...)',
    'nutrition.recent_shelf_title': '🕒 FREQUENT / RECENT FOODS (Last 20)',
    'nutrition.no_foods_found': 'No foods found matching that query.',
    'nutrition.create_custom_btn': "Can't find your food? + Create custom",
    'nutrition.cat_all': 'All',
    'nutrition.cat_recent': '🕒 Recent (20)',
    'nutrition.cat_recipes': '🥞 My Recipes',
    'nutrition.cat_beverages': '☕ Beverages, Coffee & Alcohol',
    'nutrition.cat_fruits': '🍌 Fruits',
    'nutrition.cat_grains': '🌾 Grains & Carbs',
    'nutrition.cat_veggies': '🥗 Vegetables',
    'nutrition.cat_meats': '🥩 Meats & Eggs',
    'nutrition.cat_legumes': '🫘 Legumes',
    'nutrition.cat_dairy': '🥛 Dairy',
    'nutrition.cat_fats': '🥑 Healthy Fats & Nuts',
    'nutrition.cat_supplements': '⚡ Supplements & Protein',
    'nutrition.cat_prepared': '🥪 Prepared Dishes',
    'nutrition.cat_custom': '⭐ My Foods',
    'nutrition.create_recipe_btn': '🥞 + Create Recipe',
    'nutrition.save_as_recipe': '⭐ Save as Frequent Recipe',
    'nutrition.recipes_shelf_title': '🥞 MY FREQUENT RECIPES / MEALS',
    'nutrition.recipe_saved_success': 'Recipe saved successfully!',

    // Portion Panel
    'nutrition.unit_grams': 'Grams (g)',
    'nutrition.unit_units': 'Units (u)',
    'nutrition.unit_slices': 'Slices (sl)',
    'nutrition.quantity_label': 'QUANTITY:',
    'nutrition.serving_ref': 'Serving ref',
    'nutrition.btn_confirm_add': 'Add to {meal}',

    // Custom Food Creator
    'nutrition.custom_title': 'Create Custom Food',
    'nutrition.custom_subtitle': 'NEW FOOD',
    'nutrition.custom_name': 'Food name:',
    'nutrition.custom_name_placeholder': 'E.g. Oatmeal fruit smoothie',
    'nutrition.custom_category': 'Category:',
    'nutrition.custom_unit_label': 'Serving unit:',
    'nutrition.custom_per_100g': 'Per 100 grams',
    'nutrition.custom_per_unit': 'Per 1 unit / dish',
    'nutrition.custom_kcal': 'Calories (kcal):',
    'nutrition.custom_prot': 'Protein (g):',
    'nutrition.custom_carbs': 'Carbohydrates (g):',
    'nutrition.custom_fats': 'Fats (g):',
    'nutrition.custom_save': 'Save Food',

    // Coach Plan
    'coach.no_plan_title': 'No nutrition plan assigned',
    'coach.no_plan_sub': 'Your Coach has not yet prescribed a diet plan or PDF guidelines.',
    'coach.check_btn': 'Check for Plan',
    'coach.active_badge': 'ACTIVE PLAN',
    'coach.assigned_on': 'Assigned on {date}',
    'coach.daily_goals': 'Daily Targets Prescribed by Coach',
    'coach.notes_title': "Coach's Notes & Guidelines",

    // Profile & Settings
    'profile.subtitle': 'SETTINGS & HEALTH',
    'profile.title': 'My Profile & Settings',
    'profile.language_section': 'APPLICATION LANGUAGE',
    'profile.language_sub': 'Select your preferred language',
    'profile.lang_es': '🇪🇸 Español',
    'profile.lang_en': '🇺🇸 English',
    'profile.training_prefs_title': 'WORKOUT EXPERIENCE',
    'profile.haptics_label': 'Haptic Vibration on Sets',
    'profile.haptics_desc': 'Gently vibrate when logging sets and when rest timer ends.',
    'profile.keep_awake_label': 'Keep Screen Awake',
    'profile.keep_awake_desc': 'Prevent screen from sleeping or auto-locking during workouts.',
    'profile.barbell_calc_label': 'Barbell Plate Calculator',
    'profile.barbell_calc_desc': 'Show shortcut to calculate plates needed per side on barbells.',
    'profile.unit_section': 'WEIGHT UNITS',
    'profile.biometrics_section': 'BIOMETRIC DATA & EXPENDITURE',
    'profile.edit_bio_btn': 'Edit Physical Data',
    'profile.weight': 'Weight',
    'profile.height': 'Height',
    'profile.age': 'Age',
    'profile.gender': 'Gender',
    'profile.activity_level': 'Activity Level',
    'profile.gender_male': 'Male',
    'profile.gender_female': 'Female',
    'profile.act_sedentary': 'Sedentary (Little exercise)',
    'profile.act_light': 'Light (1-3 days/week)',
    'profile.act_moderate': 'Moderate (3-5 days/week)',
    'profile.act_very_active': 'Very Active (6-7 intense days)',
    'profile.logout': 'Log Out',
    'profile.delete_account': 'Delete Account',

    // Workout Progression and Original Plan
    'workout.view_original_plan': "View Coach's Original Plan",
    'workout.original_modal_title': "Coach's Original Plan",
    'workout.original_modal_subtitle': 'OFFICIAL PRESCRIPTION VS ACTUAL PROGRESS',
    'workout.adapted_badge': '⚡ Adapted from your last session',
    'workout.coach_plan_badge': '💪 Official Coach Plan',
    'workout.reset_all_btn': '↺ Reset All to Original Plan',
    'workout.reset_exercise_btn': 'Reset to original',
    'workout.reset_confirm_title': 'Reset to original routine?',
    'workout.reset_confirm_desc': "All sets, reps, and weights will be reset to your Coach's original prescription.",
    'workout.reset_exercise_confirm_desc': "Sets and weights for this exercise will be reset to your Coach's prescription.",
    'workout.original_values': "Coach's Prescription:",
    'workout.current_values': 'Your Current Values:',
    'workout.no_modifications': "Your current workout matches 100% with the Coach's prescription.",
    'workout.has_modifications': 'You have adapted this workout based on your latest weights and sets.',
    'workout.series_count': '{count} sets',
    'workout.extra_series': 'Extra set',

    // Exercise Management & Student Inventory
    'workout.add_exercise_to_session': '+ Add Exercise to this workout',
    'workout.remove_exercise': 'Remove exercise',
    'workout.remove_exercise_confirm_title': 'Remove exercise?',
    'workout.remove_exercise_confirm_desc': 'Do you want to remove {name} from today\'s workout?',
    'workout.replace_exercise': 'Substitute exercise',
    'workout.library_title': 'Exercise Library',
    'workout.library_subtitle': 'OFFICIAL CATALOG & YOUR EXERCISES',
    'workout.tab_all': 'All',
    'workout.tab_defaults': 'Coach Defaults',
    'workout.tab_my_exercises': 'My Exercises',
    'workout.search_placeholder': 'Search by name or muscle...',
    'workout.custom_badge': 'Custom',
    'workout.create_custom_btn': '+ Create Exercise',
    'workout.new_exercise_title': 'Create Exercise',
    'workout.new_exercise_sub': 'WILL BE SAVED IN YOUR PERSONAL INVENTORY',
    'workout.exercise_name_label': 'Exercise Name',
    'workout.exercise_name_placeholder': 'e.g., Incline cable bicep curl',
    'workout.muscle_group_label': 'Muscle Group',
    'workout.description_label': 'Description / Form Technique (Optional)',
    'workout.description_placeholder': 'Key cues, posture, tempo or breathing...',
    'workout.media_url_label': 'Video or Photo URL (Optional)',
    'workout.media_url_placeholder': 'https://example.com/video.mp4',
    'workout.save_exercise_btn': 'Save and Use Exercise',
    'workout.exercise_saved_success': 'Exercise created successfully!',
    'workout.select_exercise_to_add': 'Tap to add to your workout',
    'workout.create_routine_btn': 'Create my Routine',
    'workout.create_routine_title': 'Create my Routine',
    'workout.create_routine_sub': 'NEW ROUTINE',
    'workout.routine_title_label': 'Routine Name',
    'workout.routine_title_placeholder': 'e.g., My Hypertrophy Program',
    'workout.routine_saved_success': 'Routine saved and activated successfully!',

    // Main Dashboard of Routines by Muscle Group
    'routines.dashboard_title': 'My Routines',
    'routines.dashboard_subtitle': 'Choose a muscle group or create your routine',
    'routines.total_workouts': '{count} total completed workouts',
    'routines.completed_badge': '🔥 Completed {count} times',
    'routines.completed_single': '🔥 Completed 1 time',
    'routines.completed_zero': '✨ Not started yet (0 times)',
    'routines.last_trained': 'Last trained: {time}',
    'routines.last_today': 'Today',
    'routines.last_yesterday': 'Yesterday',
    'routines.last_days_ago': '{days} days ago',
    'routines.last_never': 'Never completed',
    'routines.start_routine_btn': 'Start Workout ➔',
    'routines.back_to_dashboard': '← Back to My Routines',
    'routines.exercises_count': '{count} exercises',
    'routines.create_custom_split': '+ Create my Routine',
    'routines.explore_catalog': 'Exercise Catalog',
    'routines.in_progress_badge': 'Session #{number} in progress',
    'routines.all_muscle_groups': 'MUSCLE GROUPS',
    'routines.not_assigned': 'No exercises assigned',
    'routines.not_assigned_sub': 'Your Coach has not added exercises for this muscle group yet.',
    'routines.train_group': 'Train {group} ➔',
    'routines.assigned_by_coach': 'Assigned by Coach',
    'routines.multiple_splits_notice': 'You can train multiple muscle groups today (e.g. Chest and then Triceps). Each will add its own +1.',
    'routines.empty_group_alert_title': 'Empty Muscle Group',
    'routines.empty_group_alert_msg': 'Your Coach has not assigned a routine for {group} yet. You can request an assignment or explore the exercise catalog.',

    // Caloric Reports & Cumulative Balance
    'report.subtitle': 'ENERGY BALANCE & SAVINGS',
    'report.title': 'Cumulative Calorie Report',
    'report.open_button': '📊 View Calorie Reports (1D - 1 Month)',
    'report.tab_1d': '1 Day',
    'report.tab_7d': '7 Days',
    'report.tab_14d': '14 Days',
    'report.tab_30d': '30 Days',
    'report.tab_months': 'Months',
    'report.deficit_badge': 'CUMULATIVE CALORIC DEFICIT (SAVED)!',
    'report.surplus_badge': 'CUMULATIVE CALORIC SURPLUS',
    'report.deficit_explanation': 'During this period you consumed less than you burned. This savings is equivalent to reduced body fat.',
    'report.surplus_explanation': 'During this period you consumed a net surplus of calories above daily burn. Ideal for muscle mass gain or bulking.',
    'report.intake_label': 'TOTAL INTAKE',
    'report.expenditure_label': 'TOTAL BURN',
    'report.base_label': 'DAILY BASE',
    'report.exercise_label': 'EXERCISE TOTAL',
    'report.avg_label': 'Avg:',
    'report.strength_cardio_sum': 'Workouts + Cardio sum',
    'report.archive_month_title': 'Save Archive for this Month',
    'report.archive_month_desc': 'Stores this monthly record in historical archives to track long-term progress.',
    'report.save_btn': 'Save Month',
    'report.saved_btn': 'Saved!',
    'report.daily_breakdown_title': 'DAY BY DAY BREAKDOWN',
    'report.archives_title': 'HISTORICAL MONTHLY ARCHIVES',

    // Home / Workout Main Screen
    'home.greeting': 'HELLO',
    'home.today_workout': "Today's Workout",
    'home.lang_esp': '🇪🇸 ESP',
    'home.lang_eng': '🇺🇸 ENG',
    'home.unit_label': 'UNIT:',
    'home.system_metric': 'Metric (kg / cm)',
    'home.system_imperial': 'Imperial (lbs / ft)',
    'home.loading_workout': "Loading today's workout...",
    'home.no_routine_title': 'No active routine assigned',
    'home.no_routine_sub': 'Your Coach will assign a personalized program from their dashboard once ready.',
    'home.check_again': 'Sync',
    'home.fallback_title': '⚡ Pro Starter Routine Active',
    'home.fallback_sub': 'Train and log sets normally. Tap sync to check for new Coach assignments.',
    'home.sync': 'Sync',
    'home.day_badge': 'DAY {number}',
    'home.view_coach_plan': "💪 View Coach's Original Plan",
    'home.start_session': 'START WORKOUT',
    'home.finish_session': 'FINISH WORKOUT',
    'home.finish_btn': 'Finish',
    'home.start_btn': 'Start Session',
    'home.elapsed_time': 'Elapsed time',
    'home.stat_calories': 'kcal',
    'home.stat_sets': 'sets',
    'home.add_extra_set': '+ Add Extra Set',
    'home.col_set': 'SET',
    'home.col_target': 'TARGET',
    'home.col_rpe': 'RPE',
    'home.col_actual': 'LOG',
    'home.col_status': 'STATUS',
    'home.finish_confirm_title': 'Finish workout session?',
    'home.finish_confirm_desc': 'You completed {completed} of {total} scheduled sets ({rate}%). Do you want to finalize and save today\'s workout?',
    'home.btn_finish_save': 'Yes, Finish and Save',
    'home.btn_keep_training': 'Keep Training',
    'home.discard_title': 'Discard workout session?',
    'home.discard_desc': 'You have not completed any sets in this workout. Do you want to discard it?',
    'home.discard_btn': 'Discard',
    'home.rest_timer_title': 'REST BETWEEN SETS',
    'home.add_cardio_btn': '+ Add Cardio or Activity',

    // Workout Summary Modal
    'summary.title': 'Workout Completed!',
    'summary.subtitle': 'Outstanding effort. Every set and minute moves you closer to your peak potential.',
    'summary.time': 'TIME',
    'summary.calories': 'KCAL',
    'summary.success': 'SUCCESS',
    'summary.volume': 'VOLUME',
    'summary.continue_btn': 'Continue to Home',

    // Cardio & Extra Activities (CardioExtrasSection)
    'cardio.title': 'Cardio & Sports',
    'cardio.subtitle': 'Live stopwatch and activity logger.',
    'cardio.live_timer_badge': 'LIVE STOPWATCH',
    'cardio.paused_timer_badge': 'STOPWATCH PAUSED',
    'cardio.elapsed_time': 'Elapsed time',
    'cardio.estimated_burn': 'Estimated burn',
    'cardio.pause_btn': 'Pause',
    'cardio.resume_btn': 'Resume',
    'cardio.stop_save_btn': 'Stop and Save',
    'cardio.add_activity_btn': '+ Log Activity',
    'cardio.edit_modal_title': 'Edit Logged Activity',
    'cardio.manual_modal_title': 'Log Activity / Sport',
    'cardio.duration_label': 'Duration (minutes):',
    'cardio.incline_label': 'Incline (°):',
    'cardio.speed_label': 'Speed (km/h):',
    'cardio.resistance_label': 'Resistance Level:',
    'cardio.calc_burn_preview': 'Estimated energy burn:',
    'cardio.start_timer_btn': '⏱️ Start Live Stopwatch',
    'cardio.save_manual_btn': 'Save Activity',
    'cardio.tab_stopwatch': '⏱️ Live Stopwatch',
    'cardio.tab_manual': '✍️ Manual Entry',

    // Cardio Types
    'cardio.type.treadmill': 'Incline Treadmill',
    'cardio.type.stairmaster': 'StairMaster',
    'cardio.type.elliptical': 'Elliptical',
    'cardio.type.bike': 'Stationary Bike',
    'cardio.type.outdoor_walk': 'Outdoor Walk',
    'cardio.type.running': 'Running / Jogging',
    'cardio.type.outdoor_cycling': 'Outdoor Cycling',
    'cardio.type.swimming': 'Swimming',
    'cardio.type.football': 'Soccer',
    'cardio.type.tennis': 'Tennis / Padel',
    'cardio.type.golf': 'Golf (Walking)',
    'cardio.type.basketball': 'Basketball',
    'cardio.type.boxing': 'Boxing / Martial Arts',
    'cardio.type.yoga': 'Yoga',
    'cardio.type.pilates': 'Pilates',
    'cardio.type.sports': 'Various Sports',
    'cardio.type.other_sport': 'Other Activity',

    // Progress
    'progress.subtitle': 'METRICS & PROGRESSION',
    'progress.title': 'My Physical Progress',
    'progress.log_weight_btn': '+ Log Today\'s Weight',
    'progress.attendance_title': 'Attendance Log',
    'progress.weight_chart_title': 'Weight Progression',
    'progress.no_weight_records': 'No weight logs yet',
    'progress.no_weight_sub': 'Log your body weight today to visualize your progression chart in {unit}.',
    'progress.log_weight_modal_title': 'Log Body Weight',
    'progress.weight_input_label': 'Weight in {unit}:',
    'progress.notes_placeholder': 'Notes (e.g. fasted, post-workout...)',
    'progress.save_weight_btn': 'Save Record',
    'progress.saved_badge': 'Saved',
    'progress.caloric_exp_title': 'Calorie Expenditure & Reports',
    'progress.caloric_exp_sub': 'Energy burn across strength and cardio',
    'progress.period_day': 'Day',
    'progress.period_week': 'Week',
    'progress.period_month': 'Month',

    // Profile additional
    'profile.title_settings': 'Preferences & Settings',
    'profile.lang_label': 'System Language',
    'profile.lang_desc': 'Español or English throughout the app',
    'profile.unit_desc': 'Kilograms or Pounds for lifts and body weight',
    'profile.bio_title': 'Physiological Data & Biometrics',
    'profile.bio_card_title': 'Caloric Expenditure Parameters',
    'profile.update_bio_btn': 'Update My Measurements & Data',
    'profile.how_it_works': 'How do we calculate BMI, BMR and TDEE? (Scientific explanation)',
    'profile.active_membership': 'ACTIVE MEMBERSHIP',
    'profile.inactive_membership': 'MEMBERSHIP INACTIVE / PAUSED',
    'profile.inactive_title': 'Access to Workouts & Progress Restricted',
    'profile.inactive_desc': 'Your membership is paused or inactive. Contact your Coach to reactivate it.',

    // Inactive Lock
    'lock.title': 'MEMBERSHIP INACTIVE / PAUSED',
    'lock.heading': 'Access Restricted by Your Coach',
    'lock.message': 'Hi {name}, your workout and nutrition access is currently paused. Your Coach can reactivate it at any moment.',
    'lock.btn_check': 'Check Status Again',
    'lock.btn_contact': 'Contact My Coach',
    'lock.btn_logout': 'Log Out',
    // Authentication & Registration (Auth)
    'auth.brand_subtitle': 'Training & Nutrition Platform',
    'auth.welcome_title': 'Welcome, Athlete',
    'auth.register_title': 'New Athlete Registration',
    'auth.email_label': 'Email Address / User',
    'auth.email_placeholder': 'you@email.com',
    'auth.password_label': 'Password',
    'auth.password_placeholder': '••••••••',
    'auth.confirm_password_label': 'Confirm Password',
    'auth.confirm_password_placeholder': '••••••••',
    'auth.full_name_label': 'Full Name',
    'auth.full_name_placeholder': 'E.g. John Doe',
    'auth.login_btn': 'Sign In / Log In',
    'auth.register_btn': 'Sign Up / Register',
    'auth.no_account_prompt': "Don't have an account?",
    'auth.no_account_link': 'Sign up here',
    'auth.have_account_prompt': 'Already have an account?',
    'auth.have_account_link': 'Sign in',
    'auth.fill_all_fields': 'Please fill in all fields.',
    'auth.password_min_length': 'Password must be at least 6 characters.',
    'auth.passwords_dont_match': 'Passwords do not match.',
    'auth.invalid_credentials': 'Invalid email or password. Please check your credentials.',
    'auth.unconfirmed_email': 'Please confirm your email before signing in.',
    'auth.pending_activation_title': 'Account activation pending',
    'auth.pending_activation_desc': 'Check your inbox or spam folder to activate your account ({email}).',
    'auth.resend_activation_btn': 'Resend activation email',
    'auth.resending': 'Resending...',
    'auth.resend_success_title': 'Link resent!',
    'auth.resend_success_desc': 'Check your inbox or spam folder.',

    // Profile & Additional Settings
    'profile.session_title': 'Account Session',
    'profile.sign_out_btn': 'Log Out',
    'profile.compliance_title': 'Data Privacy & Account Management',
    'profile.compliance_desc': 'In compliance with Apple App Store guidelines, you may permanently delete your account and personal data.',
    'profile.delete_account_btn': 'Delete my account and all my data',
    'profile.bio_modal_subtitle': 'UPDATE BIOMETRICS',
    'profile.bio_modal_title': 'My Physiological Data',
    'profile.bio_modal_explain': 'These metrics are essential to accurately compute your daily energy expenditure, strength routines, incline treadmill, and cardio burn.',
    'profile.gender_label': 'BIOLOGICAL GENDER',
    'profile.weight_label': 'BODY WEIGHT ({unit})',
    'profile.weight_hint': 'In {unit}',
    'profile.height_label': 'HEIGHT',
    'profile.feet_label': 'FEET (FT)',
    'profile.inches_label': 'INCHES (IN)',
    'profile.body_type_label': 'BODY COMPOSITION & PHYSIQUE',
    'profile.body_standard': 'Standard',
    'profile.body_standard_sub': 'General population',
    'profile.body_athletic': 'Athletic / Muscular',
    'profile.body_athletic_sub': 'High muscle mass (lower body fat)',
    'profile.age_label': 'AGE',
    'profile.activity_level_label': 'DAILY LIFESTYLE ACTIVITY',
    'profile.save_bio_btn': 'Save Biometric Parameters',
    'profile.saving_bio': 'Saving...',
    'profile.unit_conversion_sub': 'Automatic system-wide unit conversion (kg or lbs)',

    // Missing Keys - Profile & Biometrics
    'profile.membership_inactive': 'MEMBERSHIP INACTIVE / PAUSED',
    'profile.membership_active': 'ACTIVE MEMBERSHIP',
    'profile.biometrics_section_title': 'Physiological Data & Biometrics',
    'profile.caloric_params_title': 'Caloric Expenditure Parameters',
    'profile.weight_label_short': 'BODY WEIGHT',
    'profile.height_label_short': 'HEIGHT',
    'profile.physique_profile_label': 'BODY TYPE',
    'profile.gender_age_label': 'GENDER & AGE',
    'profile.bmi_title': 'Body Mass Index (BMI)',
    'profile.bmr_title': 'Basal Metabolic Rate (BMR)',
    'profile.bmr_desc': 'Resting vital expenditure',
    'profile.tdee_title': 'Baseline Daily Caloric Expenditure',
    'profile.tdee_desc': 'BMR + Daily work/lifestyle activity (non-training)',
    'profile.how_calculated_btn': 'How do we calculate BMI, BMR & TDEE? (Scientific explanation)',
    'profile.unit_label': 'Weight Unit',

    // Missing Keys - Coach & Nutrition
    'coach.goals_title': 'Daily Goals Prescribed by Coach',
    'nutrition.confirm_add': 'Confirm and Add',
    'nutrition.custom_food_name': 'Food name:',
    'nutrition.custom_measure_unit': 'Serving unit:',
    'nutrition.custom_calories': 'Calories (kcal):',
    'nutrition.custom_save_btn': 'Save Food',

    // Missing Keys - Progress
    'progress.loading': 'Loading your progress...',

    // Missing Keys - Cardio & Extras
    'cardio.live_timer_btn': 'Start Live Stopwatch',
    'cardio.manual_reg_btn': 'Manual Entry',
    'cardio.select_activity': 'SELECT ACTIVITY',
    'cardio.time_done': 'DURATION (MINUTES)',
    'cardio.min_time_hint': 'Minimum 1 min',

    // Missing Keys - Interactive Workout
    'workout.extra_set_label': 'ADDED SET',
    'workout.coach_target_label': 'COACH TARGET',
    'workout.reps_label': 'Reps',
    'workout.weight_label': 'Weight ({unit})',

    // BioHacker Peptides
    'biohacker.badge_science': '🧬 APPLIED SCIENCE',
    'biohacker.card_title': 'BioHacker Peptides',
    'biohacker.card_subtitle': 'Discover cutting-edge bioactive peptides, cellular repair, muscle hypertrophy, and sports longevity.',
    'biohacker.cta_explore': 'Explore Scientific Guide',
    'biohacker.tab_peptides': 'Peptides',
    'biohacker.tab_benefits': 'Benefits',
    'biohacker.tab_infographic': 'Infographic',
    'workout.customize_exercise': 'Customize',
    'workout.customize_title': 'Customize Exercise',
    'workout.offline_mode_badge': 'Offline mode',
    'workout.synced_badge': 'Synced',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('es');

  useEffect(() => {
    const loadLang = async () => {
      try {
        const stored = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
        if (stored === 'es' || stored === 'en') {
          setLanguageState(stored);
        } else {
          // Primera ejecución: autodetección del idioma del sistema
          try {
            const systemLocale = Intl.DateTimeFormat().resolvedOptions().locale?.toLowerCase() || '';
            if (systemLocale.startsWith('en')) {
              setLanguageState('en');
              await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, 'en');
            }
          } catch (_) {}
        }
      } catch (e) {
        console.error('Error loading language preference:', e);
      }
    };
    loadLang();

  }, []);

  const setLanguage = async (newLang: Language) => {
    setLanguageState(newLang);
    try {
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, newLang);
    } catch (e) {
      console.error('Error saving language preference:', e);
    }
  };

  const toggleLanguage = async () => {
    const next = language === 'es' ? 'en' : 'es';
    await setLanguage(next);
  };

  const t = (key: string, fallback?: string): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.es;
    return langDict[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        toggleLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
